### ISSUE TITLE
JOPA CardinalityConstraintViolatedException durring persistence

### ISSUE THREAD

**Issue by grigobog** [kbss-cvut/bpmn2stamp#1]
Viz [Meeting notes (BG) - 2021-12-01](https://docs.google.com/document/d/13ZNk-q_3QfEpYN5rQWf8zwrBj7mRG3XuDMomGlt1-Uk/edit#)
commit 761b35bf6e32150dbcc47583a3c52c27591aef38
Kroky pro reprodukci:
1. mvn clean
2. mvn package
3. mvn aspectj-maven-plugin:1.12.6:compile
4. Zmenit cestu k vyslednemu souboru v construktoru RdfWriterService
5. Spustit BpmnReaderServiceTest#readFromXmlTest_resultShouldBePresent
Musi spadnout na radku 55: rdfWriterService.save(elements);

**Comment by blcham** [comment]
The error is:
```
cz.cvut.kbss.jopa.exceptions.RollbackException: cz.cvut.kbss.jopa.exceptions.CardinalityConstraintViolatedException: At least 1 values of attribute FlowElement.has_container expected in instance _3M86QLqlEeq4RbAg2SWqZQ, but got only 0
```

**Comment by blcham** [comment]
@grigobog Your assumptions are ok to assume that you will have 
`FlowElement.has_container`  inferred `has_flowElements`

This can be seen if you take `ontiky.owl` file in protege and start reasoner as can be seen here :
![image](https://user-images.githubusercontent.com/3962237/145249139-56d864f2-d8fc-40f6-9e3f-5ae49d643784.png)

However to see inferences in protege you had to do use a reasoner:
![image](https://user-images.githubusercontent.com/3962237/145249412-8e014aff-c0b9-40ed-9a08-aca429d719ca.png)

Same way you have to do it within your code. See my pull request which is failing but i guess you can continue from this point:
![image](https://user-images.githubusercontent.com/3962237/145249664-aad34f52-6693-4217-8a7a-2356303cdcb8.png)

In case you are not able to fix it like that, try instead of that writing a test to load `ontiky.owl` that you have created (if i uncomment all failing violations).  But for loading you need to include import triple (of course):
```
    <Ontology>
        <imports rdf:resource="http://BPMNbasedOntology"/>
    </Ontology>
```

**Comment by blcham** [comment]
Following the reading case 1.-4. i got into this issue  while runnig the test:
![image](https://user-images.githubusercontent.com/3962237/145650098-b55638a8-81c4-4b14-acd9-6711505e47d6.png)

I tried remove java.xml but had no success.

**Comment by grigobog** [comment]
Hm, seems like the problem is somehow related to JAXB library, which is used to read files with bpmn and organization structure.
Most likely it's caused by different Java version, I'm using [Amazon Corretto 11](https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html), which can be downloaded right from Intellij Idea.
If you are using Eclipse and java version is ok, the error may be caused [by unnecessary external libraries in modulepath](https://stackoverflow.com/a/58291231). This is all I could find in google for now.

**Comment by blcham** [comment]
1. with Amazon Corretto 11 i am able to run test.
2. test `readTest_whenObjectExists_inferredFieldsShouldBeSet()` does not make sense to me. It is not executable by itself :( as some other tests generates files that this test uses. Anyway, even if i let other tests to generate input files for this test, i get invalid input file and `actualElement`  within this test is null:
![image](https://user-images.githubusercontent.com/3962237/145905749-8c1358ea-7584-4ce5-8468-40ff8c121709.png)

The generated file `resources/jednani-sag-bpmn.ttl` is invalid turtle format file:
```
{
<http://onto.fel.cvut.cz/ontologies/ucl/example/jednani-sag-bpmn> a owl:Ontology .
<http://onto.fel.cvut.cz/ontologies/ucl/example/jednani-sag-bpmn> owl:imports <http://onto.fel.cvut.cz/ontologies/ucl/example/jednani-sag-organization-structure> .
}
```

Even if I fix the file and make it parsable, it does not help. Thus I am switching to `mapAndWriteTest` but I am not sure if I will be able to help ....

**Comment by grigobog** [comment]
Fixed in: https://github.com/kbss-cvut/jopa/issues/98 (0.18.1)

**Comment by blcham** [comment]
will close after tests.
