### ISSUE TITLE
Processing okamzita-reakce-na-bezpecnostni-problem fails due to missing file

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/bpmn2stamp#58]
Command:
```
cd bpmn-convertor-examples/processes/ucl
./bin/process-bpmn.sh bpmn/okamzita-reakce-na-bezpecnostni-problem.bpmn
```

Returns error:
```
2023-04-06 23:19:06,331 [,,] [main] ERROR ConverterOntologyFileReader - Input file validation failed.
java.io.IOException: File /home/blcha/projects/20doprava-ucl/git/bpmn-convertor-examples/processes/ucl/./organization-structure/okamzita-reakce-na-bezpecnostni-problem--organization-structure.xml doesn't exist
        at cz.cvut.kbss.bpmn2stamp.converter.service.ConverterOntologyFileReader.validateFile(ConverterOntologyFileReader.java:90)
        at cz.cvut.kbss.bpmn2stamp.converter.service.ConverterOntologyFileReader.readFromXml(ConverterOntologyFileReader.java:55)

```

Full log: 
[okamzita-reakce-na-bezpecnostni-problem.log](https://github.com/kbss-cvut/bpmn2stamp/files/11174505/okamzita-reakce-na-bezpecnostni-problem.log)

**Comment by blcham** [comment]
was it somehow badly exported ?

**Comment by grigobog** [comment]
As it is said in the exception description, the organization strucutre file "okamzita-reakce-na-bezpecnostni-problem--organization-structure.xml" actually does not exists. Seems like it happened due to missing data about the organization structure in the bonita archive project "okamzita-reakce-na-bezpecnostni-problem.bos".

In other words the original .bos file does not contain organization structure information. It can be seen by running the extraction command `bin/extract-bos.sh ./bos/okamzita-reakce-na-bezpecnostni-problem.bos` (in the project https://github.com/kbss-cvut/bpmn-convertor-examples) and checking both diectories:
- .../processes/ucl/.target/okamzita-reakce-na-bezpecnostni-problem/My project - does not contain folder with name "organizations" (and *.organization files inside)
- .../processes/ucl/organization-structure - does not contain the final "okamzita-reakce-na-bezpecnostni-problem--organization-structure.xml" XML file

Adding the organization structure info to the corresponding Bonita project and exporting it as a .bos file to replace the current one should solve the problem.

**Comment by blcham** [comment]
Following diagrams are problematic:
```
okamzita-reakce-na-bezpecnostni-problem
organizacni-rad
prirucka-inspektora-ozl-dl-a-ml
zpracovani-informaci-o-bezpecnosti
```

**Comment by blcham** [comment]
The issue has been fixed and related files were regenerated in https://github.com/kbss-cvut/bpmn-convertor-examples.
